# Default Config!
motd: "Das ist die Tagesnachricht"
welcomemsg: "Das ist die Willkommensnachricht"

#Datenbankanbindung
datenbank:
  user: username
  password: passwort
  servername: servername
  databasename: datenbankname

#Chats
chats:
  Allgemein:
    prefix: "&3[Allgemein] "
    suffix: ":&f "
    default: true
    defaultWriteChat: true
  LeitungIntern:
    prefix: "&4[LeitungIntern] "
    suffix: ":&4 "
    default: true
    raenge: [MOD,ADMIN,SPECIAL]

#Automatische Nachrichten
automessages:
    - "Nachricht1"
    - "Nachricht2"
    - "Nachricht3"
    - "And so on..."
automessagesinterval: 20