author: Tauncraft-Coderteam
database: false
description: Tauncrafts Server Manager
main: com.tauncraft.tauncraftservermanager.TauncraftServerManager
name: TauncraftServerManager
url: http://www.tauncraft.com
version: 0.1
permissions:
commands:
  
# Administration Commands:
  invsee:
    description: Zeigt das Inventar eines Spielers
    usage: /<command> <spieler>
  end:
    description: Zeigt die Endertruhe eines Spielers
    usage: /<command> [<spieler>]
  day:
    description: Setzt die Zeit in der Welt des Senders auf Tag
    usage: /<command>
  night:
    description: Setzt die Zeit in der Welt des Senders auf Nacht
    usage: /<command>
  kick:
    description: Kickt einen Spieler
    usage: /<command> <spieler> [<text>]...
    aliases: bb
  ban:
    description: Banned einen Spieler vom Server
    usage: /<command> <spieler> [<text>]...
    aliases: [bann, bb4ever, tschuess, banhammer, vertreib]
  unban:
    description: Entbanned einen Spieler vom Server
    usage: /<command> <spieler>
    aliases: [pardon, entban, entbann]
  restart:
    description: Bereitet den Server auf einen Restart vor
    usage: /<command> [stop]
    aliases: reboot
 
 # Chat Commands
  leitung:
    description: Sendet eine Leitungsnachricht
    usage: /<command> [<text>]...
    aliases: mod
  server:
    description: Sender eine Servernachricht
    usage: /<command> [<text>]...
  clearmsg:
    description: Sendet eine reine Nachricht ohne Formatierung (gut zum Testen)
    usage: /<command> [<text>]...
  tell:
    description: Sendet eine private Nachricht
    usage: /<command> <spieler> [<text>]...
    aliases: [tt,t,msg,whisper,pn]
    
# Config Commands
  configset:
    description: Setzt einen Wert in die Config
    usage: /<command> <pfad> [<text>]...
    
# Fun Commands
  blockhead:
    description: Setzt den Kopf des Spielers zu einem beliebigen Block
    usage: /<command> [<id>[:<subid>]]
    aliases: blockkopf
  effect:
    description: Spielt einen Effekt in der Nähe des Spielers ab und macht ihn dadurch besonders
    usag: /<command> <id>
    aliases: effekt
  head:
    description: Erstellt einen Kopf des Spielers
    usage: /<command> [<spieler>]
    aliases: kopf
    
# Punish Commands
  detonate:
    description: Lasst einen Spieler Explodieren (nicht Violet zeigen)
    usage: /<command> <spieler>
    aliases: explode
  lightning:
    description: Schleudert einen Blitz auf einen Spieler (nicht Violet zeigen)
    usage: /<command> <spieler>
    aliases: blitz
  
# Teleport Commands
  tp:
    description: Teleportiert den Sender zu einem anderen Spieler
    usage: /<command> <spieler1> [<spieler2>]
    aliases: teleport
  s:
    description: Teleportiert einen Spieler zum Sender
    usage: /<command> <spieler>
    aliases: tphere
