author: Tauncraft-Coderteam
database: false
description: Tauncrafts Server Manager
main: com.tauncraft.tauncraftservermanager.TauncraftServerManager
name: TauncraftServerManager
url: http://www.tauncraft.com
version: 0.1
permissions:
commands:
   tp:
      description: Teleportation
      usage: /<command> [arg0] [arg1]
   s:
      description: Teleportation
      usage: /<command> [arg0]
   blockhead:
     description: Block als kopf
     usage: /<command> [arg0]
   invsee:
     description: Inventar öffnen
     usage: /<command> [arg0]
   effect:
     description: Effekt abspielen
     usage: /<command> [arg0]