author: Tauncraft-Coderteam
database: false
description: Tauncrafts Server Manager
main: com.tauncraft.tauncraftservermanager.TauncraftServerManager
name: TauncraftServerManager
url: http://www.tauncraft.com
version: 0.1
permissions:
commands:
  
# Administration Commands:
  invsee:
    description: Zeigt das Inventar eines Spielers
    usage: /<command> <spieler>
  end:
    description: Zeigt die Endertruhe eines Spielers
    usage: /<command> [<spieler>]
  day:
    description: Setzt die Zeit in der Welt des Senders auf Tag
    usage: /<command>
  night:
    description: Setzt die Zeit in der Welt des Senders auf Nacht
    usage: /<command>
  kick:
    description: Kickt einen Spieler
    usage: /<command> <spieler> [<text>]...
    aliases: bb
  ban:
    description: Banned einen Spieler vom Server
    usage: /<command> <spieler> [<text>]...
    aliases: [bann, bb4ever, tschuess, banhammer, vertreib]
  unban:
    description: Entbanned einen Spieler vom Server
    usage: /<command> <spieler>
    aliases: [pardon, entban, entbann]
  restart:
    description: Bereitet den Server auf einen Restart vor
    usage: /<command> [stop]
    aliases: reboot
  seen:
    description: Gibt das Datum zurück an dem der Spieler das letzte Mal Online war
    usage: /<command> <spieler>
    aliases: [last, lastonline]
  warn:
    description: Verwarnt einen Spieler
    usage: /<command> <spieler> [<grund>]
    aliases: [vp, verwarn, verwarnpunkt, warnpunkt, wp]
  addport:
    description: Fügt einen neuen Port hinzu
    usage: /<command> <name>
    aliases: [setport,createport,portcreate,newport,portnew]
  removeport:
    description: Löscht einen Port
    usage: /<command> <name>
    aliases: [deleteport,portdelete,portremove]
  configset:
    description: Setzt einen Wert in die Config
    usage: /<command> <pfad> [<text>]...
    aliases: [setconfig,config,setconf,confset]
  group:
    description: Setzt die Gruppe eines Spielers
    usage: /<command> <name> <rang>
    aliases: [groupset,setgroup,rang,setrang,rangset]
  hidefrom:
    description: Versteckt dich vor einem Spieler
    usage: /<command> <spieler>
    aliases: hide
 
 # Chat Commands
  leitung:
    description: Sendet eine Leitungsnachricht
    usage: /<command> [<text>]...
    aliases: mod
  server:
    description: Sender eine Servernachricht
    usage: /<command> [<text>]...
  clearmsg:
    description: Sendet eine reine Nachricht ohne Formatierung (gut zum Testen)
    usage: /<command> [<text>]...
  tell:
    description: Sendet eine private Nachricht
    usage: /<command> <spieler> [<text>]...
    aliases: [tt,t,msg,whisper,pn]
  chat:
    description: Ändert den write Chat
    usage: /<command> <chatname>
    aliases: [switchchat,changechat]

# Creative Commands
  tc:
    description: Toggelt den Gamemode zwischen Creative und Survival
    usage: /<command> [<spieler>]
    aliases: [toggle,togglegm,creative]
  gm:
    description: Ändert den Gamemode
    usage: /<command> <gamemodename>|<gamemodeid>|<<spieler> <gamemodename>|<gammodeid>>
    alisases: [gamemode,switchgm,spielmodi]

# Fun Commands
  blockhead:
    description: Setzt den Kopf des Spielers zu einem beliebigen Block
    usage: /<command> [<id>[:<subid>]]
    aliases: blockkopf
  effekt:
    description: Spielt einen Effekt in der Nähe des Spielers ab und macht ihn dadurch besonders
    usag: /<command> <id>
    aliases: effekt
  head:
    description: Erstellt einen Kopf des Spielers
    usage: /<command> [<spieler>]
    aliases: kopf
  name:
    description: Ändert den Namen eines Items
    usage: /<command> <name>
    aliases: itemname
    
# Player Commands
  profile:
    description: Zeigt das Profil eines Spielers
    usage: /<command> [<spieler>]
    aliases: [info,describe]
  top:
    description: Zeigt die Spieler mit den meisten Taunpoints
    usage: /<command> [<limit>]
    aliases: [toptaunpoints,topstats]

# Punish Commands
  detonate:
    description: Lasst einen Spieler Explodieren (nicht Violet zeigen)
    usage: /<command> <spieler>
    aliases: explode
  lightning:
    description: Schleudert einen Blitz auf einen Spieler (nicht Violet zeigen)
    usage: /<command> <spieler>
    aliases: blitz
  spiderstorm:
    description: spawnt 5 böse Wölfe (nicht Violet zeigen)
    usage: /<command> <spieler>
    aliases: spider
  
# Teleport Commands
  tp:
    description: Teleportiert den Sender zu einem anderen Spieler
    usage: /<command> <spieler1> [<spieler2>]
    aliases: teleport
  s:
    description: Teleportiert einen Spieler zum Sender
    usage: /<command> <spieler>
    aliases: tphere
  port:
    description: Teleportiert einen Spieler zu einer definierten Location
    usage: /<command> <name>
    aliases: [portto,warp]
  portlist:
    description: Zeigt eine Liste aller verfügbaren Ports an
    usage: /<command> [<seitenzahl>]
    aliases: [portliste]
  tploc:
    description: Portet zu den angegebenen Koordinaten
    usage: /<command> <x> [<y>] <z>
    aliases: [tplocation,coords,coord,tpcoord,tptploc]
    